# See note in networkpolicy-ollama.yaml regarding CNI enforcement.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: webui-allow-ingress-controller
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: open-webui
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - protocol: TCP
          port: 8080